# Generated by Django 5.0.4 on 2024-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mass', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'birds',
            },
        ),
        migrations.CreateModel(
            name='Fishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mass', models.IntegerField()),
                ('size', models.IntegerField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'fishes',
            },
        ),
    ]
