# Generated by Django 5.0.4 on 2024-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('max_grown', models.IntegerField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'flowers',
            },
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('max_grown', models.IntegerField()),
                ('place_grown', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'trees',
            },
        ),
    ]
